name: listview_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/peem1.jpg
    - assets/images/peem2.jpg
    - assets/images/peem3.jpg
    - assets/images/peem4.jpg
    - assets/images/peem5.jpg
    - assets/images/peem6.jpg